[build]
  publish = "dist/angular-portfolio"
  command = "ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_FLAGS = "--legacy-peer-deps"
